language: python
sudo: false
python:
- 2.7
- 3.3
- 3.4
- 3.5
- pypi
cache: pip
install:
- pip install pytest pytest-cov coveralls flake8
- pip install futures
- pip install -e .
script:
- flake8
- py.test --cov=promise tests
after_success:
- coveralls
