language: python
sudo: false
python:
- 3.3
- 3.4
- 3.5
- pypy
cache: pip
install:
- pip install pytest pytest-cov coveralls
- pip install -e .
script:
- flake8
- py.test --cov=promise tests
after_success:
- coveralls
matrix:
  include:
    - python: "2.7"
      install:
		- pip install pytest pytest-cov coveralls
        - pip install -e .
        - pip install futures
