language: python
sudo: false
python:
- 2.7
- 3.5
- 3.6
- pypy
cache: pip
install:
- pip install -e .[test]
script:
- py.test --cov=promise tests
after_success:
- coveralls
matrix:
  fast_finish: true
  include:
  - python: '2.7'
    install: pip install flake8
    script: flake8
  - python: '3.5'
    script: |
      pip install pyre-check
      pyre --source-directory promise check
