language: python
sudo: false
python:
- 2.7
- 3.3
- 3.4
- 3.5
cache: pip
install:
- pip install pytest pytest-cov coveralls flake8
- pip install futures
- |
  if python -c 'import sys; sys.exit(1 if sys.hexversion<0x03000000 else 0)'
  then
    pip install pytest-asyncio
  fi
- pip install -e .
script:
- flake8
- py.test --cov=promise tests
after_success:
- coveralls
